version: '3.8'

services:

  app:
    container_name: cdm-web
    restart: always
    build:
      context: cdm-web
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    # env_file:
    #   - .env
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILE}
    # networks:
    #   - cdm-network

  postgres:
    container_name: cdm-postgres
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=${POSTGRES_DB}'
      - 'POSTGRES_USER=${POSTGRES_USER}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: '.env'
    # networks:
    #   - cdm-network

volumes:
  postgres_data:

networks:
  cdm-network: