version: '3.8'

services:
  frontend:
    restart: always
    container_name: cdm-frontend
    build:
      context: website-directory
      dockerfile: Dockerfile
    depends_on:
      - backend
    ports:
      - 3000:3000
  backend:
    restart: always
    privileged: true
    container_name: cdm-backend
    build:
      context: cdm-web
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - postgres-migrations
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILE}
      - DOCKER_HOST=unix:///var/run/docker.sock
    env_file: '.env'

  postgres:
    container_name: cdm-postgres
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=${POSTGRES_DB}'
      - 'POSTGRES_USER=${POSTGRES_USER}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD}'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: '.env'

  postgres-migrations:
    container_name: cdm-postgres-migrations
    build:
      context: migrations
      dockerfile: Dockerfile
    environment:
      - 'GOOSE_DRIVER=postgres'
      - 'GOOSE_DBSTRING=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=disable'
      - 'GOOSE_MIGRATION_DIR=/migrations'
      - 'GOOSE_TABLE=public.goose_migrations'
    entrypoint: >
      bash -c "goose up"
    depends_on:
      - postgres

volumes:
  postgres_data:
